# Generated by Django 2.1 on 2019-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='media'),
        ),
    ]
