# Generated by Django 2.1 on 2019-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
