# Generated by Django 2.1 on 2019-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0002_spot_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='picture',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
