# Generated by Django 2.1 on 2019-03-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0002_auto_20190303_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='spot/<pk>/media'),
        ),
    ]
