# Generated by Django 2.1 on 2019-03-03 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0004_spot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='author',
        ),
    ]
